// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tapestry.proto

package protocolBuffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Master Box
type Strand struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Strand_Online
	//	*Strand_Offline
	//	*Strand_Sent
	//	*Strand_Received
	//	*Strand_Moved
	//	*Strand_Deleted
	Payload       isStrand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strand) Reset() {
	*x = Strand{}
	mi := &file_tapestry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strand) ProtoMessage() {}

func (x *Strand) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strand.ProtoReflect.Descriptor instead.
func (*Strand) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{0}
}

func (x *Strand) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Strand) GetPayload() isStrand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Strand) GetOnline() *UserOnline {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Online); ok {
			return x.Online
		}
	}
	return nil
}

func (x *Strand) GetOffline() *UserOffline {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Offline); ok {
			return x.Offline
		}
	}
	return nil
}

func (x *Strand) GetSent() *DataSent {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Sent); ok {
			return x.Sent
		}
	}
	return nil
}

func (x *Strand) GetReceived() *DataReceived {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Received); ok {
			return x.Received
		}
	}
	return nil
}

func (x *Strand) GetMoved() *DataMoved {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Moved); ok {
			return x.Moved
		}
	}
	return nil
}

func (x *Strand) GetDeleted() *DataDeleted {
	if x != nil {
		if x, ok := x.Payload.(*Strand_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

type isStrand_Payload interface {
	isStrand_Payload()
}

type Strand_Online struct {
	Online *UserOnline `protobuf:"bytes,2,opt,name=online,proto3,oneof"`
}

type Strand_Offline struct {
	Offline *UserOffline `protobuf:"bytes,3,opt,name=offline,proto3,oneof"`
}

type Strand_Sent struct {
	Sent *DataSent `protobuf:"bytes,4,opt,name=sent,proto3,oneof"`
}

type Strand_Received struct {
	Received *DataReceived `protobuf:"bytes,5,opt,name=received,proto3,oneof"`
}

type Strand_Moved struct {
	Moved *DataMoved `protobuf:"bytes,6,opt,name=moved,proto3,oneof"`
}

type Strand_Deleted struct {
	Deleted *DataDeleted `protobuf:"bytes,7,opt,name=deleted,proto3,oneof"`
}

func (*Strand_Online) isStrand_Payload() {}

func (*Strand_Offline) isStrand_Payload() {}

func (*Strand_Sent) isStrand_Payload() {}

func (*Strand_Received) isStrand_Payload() {}

func (*Strand_Moved) isStrand_Payload() {}

func (*Strand_Deleted) isStrand_Payload() {}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPublicKey []byte                 `protobuf:"bytes,1,opt,name=user_public_key,json=userPublicKey,proto3" json:"user_public_key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Signed hash of the payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_tapestry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetUserPublicKey() []byte {
	if x != nil {
		return x.UserPublicKey
	}
	return nil
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type UserOnline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOnline) Reset() {
	*x = UserOnline{}
	mi := &file_tapestry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnline) ProtoMessage() {}

func (x *UserOnline) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnline.ProtoReflect.Descriptor instead.
func (*UserOnline) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{2}
}

type UserOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOffline) Reset() {
	*x = UserOffline{}
	mi := &file_tapestry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOffline) ProtoMessage() {}

func (x *UserOffline) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOffline.ProtoReflect.Descriptor instead.
func (*UserOffline) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{3}
}

type DataSent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardHash     string                 `protobuf:"bytes,1,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FileExtension string                 `protobuf:"bytes,3,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	FileSize      string                 `protobuf:"bytes,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSent) Reset() {
	*x = DataSent{}
	mi := &file_tapestry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSent) ProtoMessage() {}

func (x *DataSent) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSent.ProtoReflect.Descriptor instead.
func (*DataSent) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{4}
}

func (x *DataSent) GetShardHash() string {
	if x != nil {
		return x.ShardHash
	}
	return ""
}

func (x *DataSent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DataSent) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *DataSent) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

type DataReceived struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerPublicKey []byte                 `protobuf:"bytes,1,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"` // User who owns the file
	ShardHash      string                 `protobuf:"bytes,2,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`                  // Links back to DataSent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataReceived) Reset() {
	*x = DataReceived{}
	mi := &file_tapestry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReceived) ProtoMessage() {}

func (x *DataReceived) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReceived.ProtoReflect.Descriptor instead.
func (*DataReceived) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{5}
}

func (x *DataReceived) GetOwnerPublicKey() []byte {
	if x != nil {
		return x.OwnerPublicKey
	}
	return nil
}

func (x *DataReceived) GetShardHash() string {
	if x != nil {
		return x.ShardHash
	}
	return ""
}

type DataMoved struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerPublicKey []byte                 `protobuf:"bytes,1,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"`
	ShardHash      string                 `protobuf:"bytes,2,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataMoved) Reset() {
	*x = DataMoved{}
	mi := &file_tapestry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMoved) ProtoMessage() {}

func (x *DataMoved) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMoved.ProtoReflect.Descriptor instead.
func (*DataMoved) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{6}
}

func (x *DataMoved) GetOwnerPublicKey() []byte {
	if x != nil {
		return x.OwnerPublicKey
	}
	return nil
}

func (x *DataMoved) GetShardHash() string {
	if x != nil {
		return x.ShardHash
	}
	return ""
}

type DataDeleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerPublicKey []byte                 `protobuf:"bytes,1,opt,name=owner_public_key,json=ownerPublicKey,proto3" json:"owner_public_key,omitempty"`
	ShardHash      string                 `protobuf:"bytes,2,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataDeleted) Reset() {
	*x = DataDeleted{}
	mi := &file_tapestry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeleted) ProtoMessage() {}

func (x *DataDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_tapestry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeleted.ProtoReflect.Descriptor instead.
func (*DataDeleted) Descriptor() ([]byte, []int) {
	return file_tapestry_proto_rawDescGZIP(), []int{7}
}

func (x *DataDeleted) GetOwnerPublicKey() []byte {
	if x != nil {
		return x.OwnerPublicKey
	}
	return nil
}

func (x *DataDeleted) GetShardHash() string {
	if x != nil {
		return x.ShardHash
	}
	return ""
}

var File_tapestry_proto protoreflect.FileDescriptor

const file_tapestry_proto_rawDesc = "" +
	"\n" +
	"\x0etapestry.proto\x12\x06mosaic\"\xd2\x02\n" +
	"\x06Strand\x12&\n" +
	"\x06header\x18\x01 \x01(\v2\x0e.mosaic.HeaderR\x06header\x12,\n" +
	"\x06online\x18\x02 \x01(\v2\x12.mosaic.UserOnlineH\x00R\x06online\x12/\n" +
	"\aoffline\x18\x03 \x01(\v2\x13.mosaic.UserOfflineH\x00R\aoffline\x12&\n" +
	"\x04sent\x18\x04 \x01(\v2\x10.mosaic.DataSentH\x00R\x04sent\x122\n" +
	"\breceived\x18\x05 \x01(\v2\x14.mosaic.DataReceivedH\x00R\breceived\x12)\n" +
	"\x05moved\x18\x06 \x01(\v2\x11.mosaic.DataMovedH\x00R\x05moved\x12/\n" +
	"\adeleted\x18\a \x01(\v2\x13.mosaic.DataDeletedH\x00R\adeletedB\t\n" +
	"\apayload\"\x86\x01\n" +
	"\x06Header\x12&\n" +
	"\x0fuser_public_key\x18\x01 \x01(\fR\ruserPublicKey\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\f\n" +
	"\n" +
	"UserOnline\"\r\n" +
	"\vUserOffline\"\x89\x01\n" +
	"\bDataSent\x12\x1d\n" +
	"\n" +
	"shard_hash\x18\x01 \x01(\tR\tshardHash\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12%\n" +
	"\x0efile_extension\x18\x03 \x01(\tR\rfileExtension\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\tR\bfileSize\"W\n" +
	"\fDataReceived\x12(\n" +
	"\x10owner_public_key\x18\x01 \x01(\fR\x0eownerPublicKey\x12\x1d\n" +
	"\n" +
	"shard_hash\x18\x02 \x01(\tR\tshardHash\"T\n" +
	"\tDataMoved\x12(\n" +
	"\x10owner_public_key\x18\x01 \x01(\fR\x0eownerPublicKey\x12\x1d\n" +
	"\n" +
	"shard_hash\x18\x02 \x01(\tR\tshardHash\"V\n" +
	"\vDataDeleted\x12(\n" +
	"\x10owner_public_key\x18\x01 \x01(\fR\x0eownerPublicKey\x12\x1d\n" +
	"\n" +
	"shard_hash\x18\x02 \x01(\tR\tshardHashB\x12Z\x10./protocolBufferb\x06proto3"

var (
	file_tapestry_proto_rawDescOnce sync.Once
	file_tapestry_proto_rawDescData []byte
)

func file_tapestry_proto_rawDescGZIP() []byte {
	file_tapestry_proto_rawDescOnce.Do(func() {
		file_tapestry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tapestry_proto_rawDesc), len(file_tapestry_proto_rawDesc)))
	})
	return file_tapestry_proto_rawDescData
}

var file_tapestry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tapestry_proto_goTypes = []any{
	(*Strand)(nil),       // 0: mosaic.Strand
	(*Header)(nil),       // 1: mosaic.Header
	(*UserOnline)(nil),   // 2: mosaic.UserOnline
	(*UserOffline)(nil),  // 3: mosaic.UserOffline
	(*DataSent)(nil),     // 4: mosaic.DataSent
	(*DataReceived)(nil), // 5: mosaic.DataReceived
	(*DataMoved)(nil),    // 6: mosaic.DataMoved
	(*DataDeleted)(nil),  // 7: mosaic.DataDeleted
}
var file_tapestry_proto_depIdxs = []int32{
	1, // 0: mosaic.Strand.header:type_name -> mosaic.Header
	2, // 1: mosaic.Strand.online:type_name -> mosaic.UserOnline
	3, // 2: mosaic.Strand.offline:type_name -> mosaic.UserOffline
	4, // 3: mosaic.Strand.sent:type_name -> mosaic.DataSent
	5, // 4: mosaic.Strand.received:type_name -> mosaic.DataReceived
	6, // 5: mosaic.Strand.moved:type_name -> mosaic.DataMoved
	7, // 6: mosaic.Strand.deleted:type_name -> mosaic.DataDeleted
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tapestry_proto_init() }
func file_tapestry_proto_init() {
	if File_tapestry_proto != nil {
		return
	}
	file_tapestry_proto_msgTypes[0].OneofWrappers = []any{
		(*Strand_Online)(nil),
		(*Strand_Offline)(nil),
		(*Strand_Sent)(nil),
		(*Strand_Received)(nil),
		(*Strand_Moved)(nil),
		(*Strand_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tapestry_proto_rawDesc), len(file_tapestry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tapestry_proto_goTypes,
		DependencyIndexes: file_tapestry_proto_depIdxs,
		MessageInfos:      file_tapestry_proto_msgTypes,
	}.Build()
	File_tapestry_proto = out.File
	file_tapestry_proto_goTypes = nil
	file_tapestry_proto_depIdxs = nil
}
